设置dataframe输出百分比数据m

In [13]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.random(4), columns=['random'])
df

random
0  0.784334
1  0.493995
2  0.718640
3  0.235766

In [10]:
df.style.format({'random':'{0:.3%}'.format}) #{0:.3%} .3表示小数点后面有三个数字

使用百分号可以自动将数据转换为百分比格式:
'{0:.2%}'.format(0.555555)

获取第n大的数所在行

In [15]:
df = pd.DataFrame(
    np.random.randint(1, 30, 30).reshape(10,-1), 
    columns=list('abc'))
df['a']

0     7
1    22
2     1
3    23
4     4
5     9
6    20
7    16
8     8
9     2
Name: a, dtype: int32

In [18]:
# 使用行号排序
df['a'].argsort()

0    2
1    9
2    4
3    0
4    8
5    5
6    7
7    6
8    1
9    3
Name: a, dtype: int64

In [19]:
df['a'][df['a'].argsort()] # 可以这样看到原始数据的排序


2     1
9     2
4     4
0     7
8     8
5     9
7    16
6    20
1    22
3    23
Name: a, dtype: int32

In [24]:
n = 1
df['a'].argsort()[::-1][n]   #貌似好像不太对


9

dataframe获取行之和大于100的数据, 并返回最后的两行m

In [25]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
rowsums = df.apply(np.sum, axis=1)   #对所有的行进行求和  但只打印最后两行
last_two_rows = df.iloc[np.where(rowsums > 100)[0][-2:], :]
last_two_rows


0   1   2   3
9   14  39  25  30
12  28  39  15  27

如何从系列或数据框列中查找和限制异常值
用相应的5％分位数和95％分位数值替换低于5％分位数和大于95％分位数的所有值

In [26]:
ser = pd.Series(np.logspace(-2, 2, 30))

# Solution
def cap_outliers(ser, low_perc, high_perc):
    low, high = ser.quantile([low_perc, high_perc])
    print(low_perc, '%ile: ', low, '|', high_perc, '%ile: ', high)
    ser[ser < low] = low
    ser[ser > high] = high
    return(ser)

capped_ser = cap_outliers(ser, .05, .95)

0.05 %ile:  0.016049294076965887 | 0.95 %ile:  63.876672220183934


如何在删除负值后将dataframe重新整形为最大可能的正方形
将df重塑为最大可能的正方形，并删除负值。如果需要，删除最小值。结果中正数的顺序应保持与原始顺序相同。

In [27]:
df = pd.DataFrame(np.random.randint(-20, 50, 100).reshape(10,-1))
print(df)

    0   1   2   3   4   5   6   7   8   9
0  32 -13  32 -17  44  -8  18  12   8  30
1   0 -11   1 -10  43   4  28 -15  16  -5
2  45  18   5  35  -2  38 -16  19  28  30
3  -7  32  32  27 -17  23  14   8  39  41
4 -11  13  41  -4   8 -13 -17 -15  27  25
5  -9  16   5  38   9  22  44 -12  31 -13
6 -13  36   9  42  21  20  45  32  45 -17
7  11   7  43  30  15  31 -13  35   2  30
8   6  39  24  28  11  27  48  13  29   1
9  20  24  49  -2  34  40  24  23  -4   5


In [28]:
# 删除负数

arr = df[df > 0].values.flatten() #只打印大于0的数
arr_qualified = arr[~np.isnan(arr)]
arr_qualified

array([32., 32., 44., 18., 12.,  8., 30.,  1., 43.,  4., 28., 16., 45.,
       18.,  5., 35., 38., 19., 28., 30., 32., 32., 27., 23., 14.,  8.,
       39., 41., 13., 41.,  8., 27., 25., 16.,  5., 38.,  9., 22., 44.,
       31., 36.,  9., 42., 21., 20., 45., 32., 45., 11.,  7., 43., 30.,
       15., 31., 35.,  2., 30.,  6., 39., 24., 28., 11., 27., 48., 13.,
       29.,  1., 20., 24., 49., 34., 40., 24., 23.,  5.])

In [29]:
# 计算正方形的边长
n = int(np.floor(arr_qualified.shape[0]**.5))  #边长肯定是整数
n

8

In [30]:
#  整形为要求的正方形
top_indexes = np.argsort(arr_qualified)[::-1]
output = np.take(arr_qualified, sorted(top_indexes[:n**2])).reshape(n, -1)
print(output)

[[32. 32. 44. 18. 12. 30. 43. 28.]
 [16. 45. 18. 35. 38. 19. 28. 30.]
 [32. 32. 27. 23. 14. 39. 41. 13.]
 [41.  8. 27. 25. 16. 38.  9. 22.]
 [44. 31. 36.  9. 42. 21. 20. 45.]
 [32. 45. 11. 43. 30. 15. 31. 35.]
 [30. 39. 24. 28. 11. 27. 48. 13.]
 [29. 20. 24. 49. 34. 40. 24. 23.]]


交换dataframe的两行

In [31]:
df = pd.DataFrame(np.arange(25).reshape(5, -1))
df

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [32]:
a, b = df.iloc[1, :].copy(), df.iloc[2, :].copy()  #交换第一行和第二行
df.iloc[1, :], df.iloc[2, :] = b, a
df

0   1   2   3   4
0   0   1   2   3   4
1  10  11  12  13  14
2   5   6   7   8   9
3  15  16  17  18  19
4  20  21  22  23  24

计算 每行的最近行(使用欧几里得距离)

In [33]:
nearest = {}
for i, row in df.iterrows():
    c = ((df - row)**2).sum(axis = 1).argsort()
    for j in c:
        if j != i:
            break
    nearest[i] = j
print(nearest)

{0: 2, 1: 2, 2: 0, 3: 1, 4: 3}
